import { Arima, Arimo, Comic_Neue } from "next/font/google";
import "./globals.css";


const ComicNeue = Comic_Neue({
  variable: "--font-comic-neue",
  subsets: ["latin"],
  weight: ["400", "700","300"],
});

const arimo = Arima({
  variable: "--font-arimo",
  subsets: ["latin"],
  weight: ["400", "700","500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${arimo.variable} ${ComicNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
